apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apache-deployment
  name: apache-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: apache-deployment
    spec:
      containers:
      - image: httpd:latest 
        name: apache 
        resources:
          limits:
            cpu: 1.5
            memory: 512Mi
          requests:
            cpu: 0.75
            memory: 128Mi
        livenessProbe:
          httpGet: 
            path: /
            port: 80
          initialDelaySeconds: 7 
          periodSeconds: 7
          timeoutSeconds: 4  
          failureThreshold: 2 
        readinessProbe:
          exec:
            command:
            - curl 
            - f
            - http://localhost:80/
          initialDelaySeconds: 7 
          periodSeconds: 7
          timeoutSeconds: 4 
          failureThreshold: 2
          successThreshold: 1
        startupProbe:
          tcpSocket:
            port: 80 
          initialDelaySeconds: 10 
          timeoutSeconds: 5 
          failureThreshold: 1
          successThreshold: 1



