apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
 name: developer
spec:
 request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1dUQ0NBVUVDQVFBd0ZERVNNQkFHQTFVRUF3d0paR1YyWld4dmNHVnlNSUlCSWpBTkJna3Foa2lHOXcwQgpBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEwaFo1M05SL1J4VWlIejJWNVVHVE9nWEpVelhNSjlKSkU0TzB0ZlErCnd6d2gwNFJqQU1NZ2JJYzArZVFXbnpPdHUvSlozVDNLUjNpTWxNY05ld3lEbC8vUGkrbWxiUTB4czgrYlkrTEsKZHRpR01kTWhWaEVGZ3AxOGI0d3pCZTI1Y205ODB1YkZPd0tYVnBNRW12Z3hLTVJQM2NudURRR09nSHoxWGVEVgp0U0IyZHpFUFIzTkdkZnRNY2pvY1hGNzE0MnlOd1pZOUE2djMrN3E2a2laN2VZeEZ4NCtyY1kzeHUzYitPWmlJCit5azNKcEFweDZZNVNMOENsT3l2YjlXOTFMbkVrUFhQS3lJQWJkOXo1UzluVWg2ZjYvcWxJNVNRTXIvUSs4WVAKZERHQU8zMlpEUjA0YzA0Snl5cnNuRTEwQjdPOVd1NGJQb0t2OWtiT3c1cGlOd0lEQVFBQm9BQXdEUVlKS29aSQpodmNOQVFFTEJRQURnZ0VCQUMxeWZtZnNGK2lNTHQyMjRPdWpiamhwaURGNk1HZUNpcDh1Zm8wSXE1aHNIdHA2CmFpUWs5YmxzR2RSOU5JK1VnZ3ZJeHpSYk1UVllQTndrV2ROQlRRZ05oZ0xTdSt2YXovbWtQRjhnNkl6cnBEYXAKUDVnOGt2aVJnaVlicG1WaHlKTGo3RDFQb2hTWFUxYnF6b0k3anBubWZPaTZVMnFya0lDcDFKODF5WVNSbFlFNApsUUhKRHhGbHJQOXBmV0NFN1poblRqYzdDL3JNczNWV2YxcS80clNOL2N2VGJ0U1A0QVR0ZjVhc1lYMWxQTzFLCmdGK20wUGs4Y2FUZFloRzNpTVgrTjRnY2hxWWhuZWtNUk5Ebkk3a2dJV0kwVHp2SzMrRVhnRFYwZU5hSW1iaFoKdm10QUthRHhsay9xdWlmZk1yOHBwLzFjV1lQV09qcmd6b1RLLzhNPQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K 
 signerName: kubernetes.io/kube-apiserver-client
 expirationSeconds: 31536000 # 1 year
 usages:
 - client auth











