apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
 name: developer
spec:
 request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1dUQ0NBVUVDQVFBd0ZERVNNQkFHQTFVRUF3d0paR1YyWld4dmNHVnlNSUlCSWpBTkJna3Foa2lHOXcwQgpBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFvaUNxamVwVFV3NDZsaVdERWJDVHFuT1N2QWNHWDZDcUQ5U0x0ZytlCjZYNHJOUSs3ckZiWjhmUE5PcWZvdWl0ak1Ic0oxYVhDTlFaUVJHYmx1SGZHU2ptV2YvZDhIeHpYWDNUMDI2Sk0KNnY3ditDQkU3RnAyQmJPTlBjT3kveTJqYTZFNVFwSk9vQWQ0V0taMEYxN0tpZkF5aUJacmhEeVZWV3dFZk5kegpDelhFZ3crd1c3amY2WUVReDVIZC9KQXBJa0lqSm9oa3MyRmpCQndpT1NJZ1N1OCtHNHRBMG9qdHhwZXoyZXU2CldkRGp5cmJqOVloU0EyaG9NWmVXMmdDYjRLY3BYaUdSUHBQdStPejJvd2dUNnVuT3NaWmQ1MjZWcEhXR3pra3gKT0ZJcy90VnNldm9KL0llTkZhU3R1OXBRanRRYllmMWd5c2lGaUdVK0ZndEtFUUlEQVFBQm9BQXdEUVlKS29aSQpodmNOQVFFTEJRQURnZ0VCQUVnRFQxNnZITTI5MlQwMVJRKzdic1ZwU2todmpScUJSdUFUVWhyRXYydENQSUtvCklOV2JhREhwS3RzVlBqR2ZCb21PRXMxclltc2hGcWY0SnVnWkRPSDBUeUJLTEF5dUV5bXdjbm1ueElvQ3hQZFgKQ0NUV0Z6Z0dYRVpsVW13dlUxT2ZEZFVWYW15Njg3aWpuckRIN25mQWNSZjc0TVQ3NHEyTHkwZit2dG9lUXo4cwpoa0h3Y2I3Nlp1cDR4U29GQmFkUHJlcUs0STdkMVRkQ0h5RzVUV3VOTHpnamZqdTBqYy9VWHUwL1hkeXY3M1c4CnZVcG95MFZ2UUNSb2NVT2IrOGdydEpiVnFZOCtvQkNIWUgvT0h3dFJNUCtpbkdPbHFtb3JQaG5pNWwzN1hhdjgKaWpaZFBJMjB5YjZXaFRzeFhycUcxajVnY29SeWhxKzVUMTl1Z0lVPQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K 
 signerName: kubernetes.io/kube-apiserver-client
 expirationSeconds: 31536000 # 1 year
 usages:
 - client auth











