apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
 name: platform 
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1dEQ0NBVUFDQVFBd0V6RVJNQThHQTFVRUF3d0ljR3hoZEdadmNtMHdnZ0VpTUEwR0NTcUdTSWIzRFFFQgpBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ1Q0Q2t2MVd4VUFYN0Qza3V3SHlrYllibmZQMHljVDRod0RRYVlObUVLCjQxMVhveHVjNGhkcVNrR3FDY1pONVZJMDZmSkJGQVQ1Tm56SXJJL2o2V2JvNklSVU1TZU4vK2Q0TG82cjIrdi8KNXFSMFRLeE5FY0RlQ2pGaHhVSTlTWTNrc28xTFh4QmNoakFFS0JUT0FuSkJ1QXZqVzlxalBKdCtxbE5TRkNTaQpqL0dNUXRHdUk0akdwZHU1d05NSnltMFFpYXpMQy9TWFBCcEREcDMydVVsSzZ0RXVpMlljb3RqZDBWa2UzdnZoCm40aHE5c3FpYVFYL0NaV0Juc3RUbWJ1b3h0TldYeG16aDRnbnYvK1J1WW5TUFl6a0NFa3hBSTdEZktrNEFCSDkKc2NGeWZUZ3RESGZNT0tqc2o5ekpMbkxUU2d3bXhPZmZSZGc3c01oa3hRam5BZ01CQUFHZ0FEQU5CZ2txaGtpRwo5dzBCQVFzRkFBT0NBUUVBZHpuUnJ0SmI4MzgxNVlFM1NpNFplMFgzTlZiWmJ5SCttVmtKMmNCZCtRWTZ4YTI5CjNpay93UEJOL2FDazBSOHVnK0FGcHg1RlRIck0rSE5uRGtYTTU4bTAvcXN0TFZhc3JnZWRrRFlTbm9rZXhMUGYKQXE0QlpodktiNkRCelJCVXJDVGpIcmd1RTdqKzFnWXVpT0ZaSWNFekV4U1F1dmxLdU9xRGNzT09IRi9PUDhxaQprYmw3dHlOUFBuRnpqc1p3WEk5WHo2cW5xRnpVcUw0UExOKzh4RzhuT0hkWUZSaElRRElLK3liZzZ5MlJVc2NLCnhKdkZITnpQVVk2YSswbWgrQTYvNS9zMmt2WmtqT0p4b0NyejJpK05nbFQxbUYyU0tYYmtDRjlWU1cwRWhaNDIKQUZ2aW9SVXpIcTdnai9NdjNMRWprNURwRGRYUlpOZ1JzYThpdnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 31536000 # 1 year
  usages:
  - client auth











